---
- name: Monday morning review
  connection: local
  hosts: ansibleController
  gather_facts: no

  tasks:
    - name: Http lookup to alta3.com
      ansible.builtin.uri:
        url: https://alta3.com
      register: results

    - name: Display results
      ansible.builtin.debug:
        var: results

    - name: do sometbhing strange
      debug:
        msg: "Strangeness happens here"
